### PR TITLE
Get specific params

### PR DESCRIPTION
**Pull request by ruthmccabe**
**Pull Request**

Thanks for your contribution to `epireview`! Please include the following information:

* A description of this PR, and why it is needed.
This responds to issue #23 and has functions to get specific parameters of interest.

* A summary of the changes.
Additional functions to pull specific parameters of interest, combining get_key_cols and get_parameter functionalities (the latter of which was updated for this use-case).  All in get_parameter.R.

* Links to any issues it fixes.
#23 

**Checklist**:

 - [x] I have added new dependencies in `DESCRIPTION`
 - [x ] I have bumped the version number in `DESCRIPTION` - yes but I think is out of date due to other releases
 - [x] I have updated the `NEWS.md`
 - [x] I have added unit tests using `testthat`
 - [ ] I have checked that the package can install locally using `devtools::install_local("<path-to-epireview>")` 
 - [x] I have added documentation where required
 - [x] My documentation includes examples of how to use the function
 - [x] If necessary, I have updated [`priority-pathogens`](https://github.com/mrc-ide/priority-pathogens)

### CODE REVIEW

**Comment by sangeetabhatia03** [comment]
@ruthmccabe @joshwlambert  thanks for your work on this, it is a very neat implementation. I think we should give the user  the option of retrieving all columns if they want? I suggest adding an argument to get_key_cols that takes in something like "all", "key" and returns all columns if the user wants them. If you agree, I am happy to implement this change if you don't have the bandwidth.

**Comment by ruthmccabe** [comment]
Thanks @sangeetabhatia03! To be clear all of the neatness comes from @joshwlambert!
Yes that sounds good and happy to work on that this morning

**Comment by ruthmccabe** [comment]
Sorry team for the delay, this WHO visit is dominating my time right now but I promise I will get to this by the end of next week latest! @sangeetabhatia03 @joshwlambert

**Comment by ruthmccabe** [comment]
@sangeetabhatia03 this is now ready for review :)

**Comment by sangeetabhatia03** [comment]
Thanks @ruthmccabe  and @joshwlambert , this is really great. I did make one major change - instead of passing all_columns argument via ... I have used specific argument name in functions to get specific parameters. Do let me know if you disagree with this approach. 
Other changes
- used isTRUE instead of == to check all_columns
- Updated examples
- Updated tests; parameter_class is a mandatory column via Ruth's earlier PR so added this to mock data.

**Review by sangeetabhatia03 — APPROVED** [review]
Approved with changes as noted in comments

**Pull request merged**
