### PR TITLE
Clean-up epireview

### PR DESCRIPTION
**Pull request by sangeetabhatia03**
This PR follows on Tristan's PR that cleans up the vignettes. This PR:
- fixes all examples in the documentation (many of them didn't work);
- removes examples from functions that add data as this functionality needs more thinking about;
- updates tests so that they all pass now;
- updates documentation to deal with all notes and warnings issued during the build process.

The package now builds without any errors and all tests pass. Bumping up version number is not needed because we are not adding any new functionality.

To test this PR, clone the repository or pull the latest changes from this branch if already have a clone. Then in an R session, run 
```
devtools::check()
```
Expect 0 errors

### CODE REVIEW

**Comment by sangeetabhatia03** [comment]
For your attention @CosmoNaught

**Review by cm401 — APPROVED** [review]
I can run the code and devtools::checks runs fine (0 errors ✔ | 0 warnings ✔ | 1 note ✖) for me (this is on a Mac).
I can't spot any issues with the code changes from visual inspection. From running the code I still get a warning for loading Lassa data:

`Data loaded for lassa                                                                                                                    
Warning messages:
1: One or more parsing issues, call `problems()` on your data frame for details, e.g.:
  dat <- vroom(...)
  problems(dat) `

Also, the code produces NAs for some of the study labels..

`> params$article_label
  [1] "Webb 1986"              "Webb 1986"              NA                      
  [4] NA                       "Van Der Waals 1986"     "Troup 1970"            
  [7] "Troup 1970"             NA                       NA     `
  
This seems to happen because the join is by article id but we have two article ids for the same paper (from double extraction)
image
Not sure if this is a Lassa specific issue (due to the fact that the double extraction was done prior to the current code base in priority pathogens).

Forest plot for serial intervals doesn't work (fine for R_t)
`> forest_plot_serial_interval(params,ulim=100)
Error in do.call(rbind, res) : second argument must be a list
In addition: Warning message:
In invert_inverse_params(reparam_gamma(df)) : No parameters to invert.`

Forest plot for incubation period is fine.

Marburg - one issue with R_t but that's the Marburg data which I'll create an issue to fix.

Otherwise this looks good. Once this is in develop will this get merged into main straight away?

**Comment by CosmoNaught** [comment]
I have run `devtools:check()` on this branch (after merging `develop` into `clean-up` and am receiving the following errors, warnings and notes. Please see below for full detail of the message.

── R CMD check results ───────────────────────────────────────────── epireview 1.1.3 ────
Duration: 59.2s

❯ checking examples ... ERROR
  Running examples in ‘epireview-Ex.R’ failed
  The error most likely occurred in:
  
  > base::assign(".ptime", proc.time(), pos = "CheckExEnv")
  > ### Name: get_parameter
  > ### Title: retrieve all parameters of specified type
  > ### Aliases: get_parameter
  > 
  > ### ** Examples
  > 
  > df <- load_epidata(pathogen = "ebola")
  Warning: One or more parsing issues, call `problems()` on your data frame for details,
  e.g.:
    dat <- vroom(...)
    problems(dat)
  Warning in load_epidata_raw(pathogen, "outbreak") :
    No data found for  ebola
  Warning: One or more parsing issues, call `problems()` on your data frame for details,
  e.g.:
    dat <- vroom(...)
    problems(dat)
  Warning in load_epidata(pathogen = "ebola") :
    No outbreaks information found for  ebola
  Data loaded for ebola
  > get_parameter(data = df$params, parameter_name = "Human delay - serial interval")
  Error in get_parameter(data = df$params, parameter_name = "Human delay - serial interval") : 
    could not find function "get_parameter"
  Execution halted

❯ checking Rd cross-references ... WARNING
  Missing link or links in documentation object 'get_parameter.Rd':
    ‘load_epidata()’
  
  See section 'Cross-references' in the 'Writing R Extensions' manual.

❯ checking package dependencies ... NOTE
  Package suggested but not available for checking: ‘meta’

1 error ✖ | 1 warning ✖ | 1 note ✖

## Can someone please clarify the following:
- Confirming if `get_parameter` is correctly exported and documented. This will be fixed by the following push, unsure why others weren't getting this, my version of this branch was missing the '# @export' tag
- Ensuring correct linkage in Rd files, especially for `load_epidata()`. Though this is a warning.
- Advice on handling the `meta` package in Suggests, if necessary. This is just a note. 

Any insights or suggestions would be greatly appreciated!

Some FYI:

## System Information
- R version 4.3.3 (2024-02-29)
- Platform: x86_64-redhat-linux-gnu (64-bit)
- Using R under: Fedora Linux 39

**Comment by CosmoNaught** [comment]
## Issues found
-  `get_parameter` is now correctly exported and documented. Have pushed fix to branch.
- Ensuring correct linkage in Rd files, especially for `load_epidata()`, to resolve the documentation warning. The warning clearly arises from this double commenting @sangeetabhatia03 can we enable this function please? https://github.com/mrc-ide/epireview/blob/a150eb0c90af347053b34d8d4256fda992d9abcc/R/prep_data_forest_plots.R#L43-L67
- Please advise on handling the `meta` package in `Suggests`. Unsure if necessary for package but I would suggest moving to `Imports` if possible.

Please advise on how to proceed. Other than this the branch passes all checks now (bar the following)

```
── R CMD check results ───────────────────────────────────────────── epireview 1.1.3 ────
Duration: 3m 28.3s

❯ checking Rd cross-references ... WARNING
  Missing link or links in documentation object 'get_parameter.Rd':
    ‘load_epidata()’
  
  See section 'Cross-references' in the 'Writing R Extensions' manual.

0 errors ✔ | 1 warning ✖ | 0 notes ✔
```

## System Information
- R version 4.3.3 (2024-02-29)
- Platform: x86_64-redhat-linux-gnu (64-bit)
- Using R under: Fedora Linux 39

**Pull request merged**
